### ISSUE TITLE
遍历测试报java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by summerbuild** [baidu/Cafe#19]
error message="java.lang.StringIndexOutOfBoundsException: length=88; regionStart=0; regionLength=-1" type="java.lang.StringIndexOutOfBoundsException">java.lang.StringIndexOutOfBoundsException: length=88; regionStart=0; regionLength=-1
    at java.lang.String.startEndAndLength(String.java:583)
    at java.lang.String.substring(String.java:1464)
    at com.baidu.cafe.local.traveler.Operation.getTypeString(Operation.java:288)
    at com.baidu.cafe.local.traveler.Operation.isTheSameView(Operation.java:271)
    at com.baidu.cafe.local.traveler.Operation.equals(Operation.java:212)
    at java.util.ArrayList.indexOf(ArrayList.java:354)
    at com.baidu.cafe.local.traveler.APPTraveler.updateNodeChildren(APPTraveler.java:408)
    at com.baidu.cafe.local.traveler.APPTraveler.travel(APPTraveler.java:122)
    at com.baidu.cafe.local.LocalLib.travel(LocalLib.java:2335)
    at com.baidu.cafe.local.LocalLib.travel(LocalLib.java:2343)
    at com.baidu.cafe.test.CafeTraveler.test_travel(CafeTraveler.java:39)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
    at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
    at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
    at junit.framework.TestCase.runBare(TestCase.java:134)
    at junit.framework.TestResult$1.protect(TestResult.java:115)
    at junit.framework.TestResult.runProtected(TestResult.java:133)
    at junit.framework.TestResult.run(TestResult.java:118)
    at junit.framework.TestCase.run(TestCase.java:124)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:190)
    at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:175)
    at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
    at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1667)

**Comment by luxiaoyu** [comment]
数组越界的原因是4.2以后的view.toString内容发生了变化，修复详情如下
https://github.com/BaiduQA/Cafe/commit/833a9d5bfcf7c3bdab412592f6a30a04c80c1b14
